/* ============================================================
   Mottainai Connect - Language System
   ------------------------------------------------------------
   1つの言語ファイルで全ページを翻訳します。
   新しい文章を追加するときは translations のキーを追加し、
   HTML側に data-i18n="そのキー" を付けてください。
   ============================================================ */

const LANGUAGES = [
  "ja",
  "en",
  "zh",
  "ne",
  "bn",
  "vi",
  "ta",
  "my",
  "id",
  "fil",
  "pt",
  "ko",
];
const LANGUAGE_NAMES = {
  ja: "日本語",
  en: "English",
  zh: "中文",
  ne: "नेपाली",
  bn: "বাংলা",
  vi: "Tiếng Việt",
  ta: "தமிழ்",
  my: "မြန်မာဘာသာ",
  id: "Bahasa Indonesia",
  fil: "Filipino",
  pt: "Português",
  ko: "한국어",
};

const translations = {
  ja: {
    "nav.about": "Mottainai Connectとは",
    "nav.how": "使い方",
    "nav.faq": "よくある質問",
    "nav.give": "あげる／売る",
    "nav.receive": "もらう／買う",
    "nav.login": "ログイン",
    "nav.logout": "ログアウト",
    "hero.title": "近所の いらないもの・無料のものを探す",
    "hero.subtitle": "日本で家具を すてる・もらうのが簡単になります。",
    "hero.searchPlaceholder": "郵便番号を入力（例：160-0022）",
    "hero.searchBtn": "検索",
    "hero.stat1": "やりとりされたアイテム",
    "hero.stat2": "対応言語",
    "hero.stat3": "ボランティア謝礼",
    "actions.giveTitle": "ものをあげる／売る",
    "actions.giveDesc": "使わなくなったものを写真つきで簡単に出品",
    "actions.receiveTitle": "ものをもらう／買う",
    "actions.receiveDesc": "欲しいものと予算を伝えてリクエスト",
    "how.title": "使い方はとてもシンプルです",
    "how.step1Title": "探す",
    "how.step1Desc": "郵便番号や地域から、近くのアイテムを探します。",
    "how.step2Title": "連絡する",
    "how.step2Desc": "出品者やリクエストした人にメッセージを送ります。",
    "how.step3Title": "受け取る",
    "how.step3Desc": "自分で取りに行くか、ボランティアにお願いします。",
    "products.heading": "いまいる場所から 5km のもの",
    "common.volunteerOk": "ボランティア利用可",
    "p1.badge": "無料",
    "p1.title": "木製のリラックスソファ",
    "p1.location": "新宿区",
    "p1.distance": "1.2 km",
    "p1.btn": "欲しい",
    "p2.title": "ミニ自転車（状態良好）",
    "p2.location": "渋谷区",
    "p2.distance": "3.5 km",
    "p2.btn": "連絡する",
    "p3.title": "電子レンジ（動作確認済み）",
    "p3.location": "江東区",
    "p3.distance": "4.0 km",
    "volunteer.title": "自分で取りに行くのが難しいときは？",
    "volunteer.body":
      "「ボランティアサービス」を選ぶと、地域のサポーターが代わりに荷物を受け取り、あなたまで届けてくれます。",
    "volunteer.bonus":
      "お礼はたったの300円から。サポーターにも感謝を伝えられます。",
    "volunteer.cta": "ボランティアを依頼する",
    "about.title": "Mottainai Connectとは？",
    "about.body":
      "日本で暮らす外国人・留学生が、引っ越しや帰国のときに困る「不要品の処分」と「生活用品の入手」を、地域の「あげる・もらう」の輪でつなぐサービスです。ことば・地域・慣習の違いがあっても、安心して物のやりとりができる場所を目指しています。",
    "stats.stat1": "不要な家具を再利用",
    "stats.stat2": "対応する出身国・地域",
    "stats.stat3": "粗大ごみの削減",
    "safety.title": "安心・安全にご利用いただくために",
    "safety.item1":
      "初めての取引は、なるべく人通りの多い場所で受け渡しをしましょう。",
    "safety.item2":
      "やりとりはできるだけアプリ内のメッセージで行い、記録を残しましょう。",
    "safety.item3": "不審な相手や不適切な投稿は、遠慮なく通報してください。",
    "safety.item4":
      "ボランティアはすべて本人確認済みのメンバーのみが対応します。",
    "faq.title": "よくある質問",
    "faq.q1": "利用料金はかかりますか？",
    "faq.a1":
      "閲覧や検索、メッセージのやりとりは無料です。ボランティアに依頼する場合のみ、少額の謝礼（300円〜）が発生します。",
    "faq.q2": "日本語が話せなくても使えますか？",
    "faq.a2":
      "はい。やさしい日本語のほか、英語・ベンガル語・ネパール語・中国語などに対応しています。右上の言語ボタンから切り替えられます。",
    "faq.q3": "受け取りの日時はどう決めますか？",
    "faq.a3":
      "出品者・希望者どうしでメッセージをやりとりし、都合の良い日時と場所を相談して決めます。",
    "faq.q4": "壊れているものでも出品できますか？",
    "faq.a4":
      "状態は必ず正直に記載してください。「ジャンク品」として、部品取りや修理目的で欲しい人が見つかることもあります。",
    "finalcta.title": "今日から、もったいないを、つながりに。",
    "finalcta.body":
      "使わなくなったものが、誰かの「助かった」になる。まずは近くのアイテムを探してみましょう。",
    "finalcta.giveBtn": "ものをあげる",
    "finalcta.receiveBtn": "ものをもらう",
    "footer.tagline":
      "日本で暮らす外国人・留学生のための、あげる・もらう たすけあいサービス。",
    "footer.linksTitle": "リンク",
    "footer.contact": "お問い合わせ",
    "footer.rights": "© 2026 Mottainai Connect - 卒業制作",
    "give.pageTitle": "プロダクトを出品する - Mottainai Connect",
    "give.backHome": "ホームに戻る",
    "give.formTitle": "プロダクトを出品する（あげる／売る）",
    "give.nameLabel": "プロダクト名 *",
    "give.namePlaceholder": "例：木製テーブル、ミニ冷蔵庫",
    "give.conditionLabel": "状態 *",
    "give.selectDefault": "選択してください",
    "give.conditionNew": "新品同様（Brand New）",
    "give.conditionGood": "状態が良い（Good）",
    "give.conditionUsed": "使用感あり（Used）",
    "give.priceLabel": "価格（無料なら0と入力）*",
    "give.pricePlaceholder": "例：1500 または 0",
    "give.locationLabel": "場所または郵便番号 *",
    "give.locationPlaceholder": "例：Shinjuku, 160-0022",
    "give.descLabel": "詳しい説明 *",
    "give.descPlaceholder":
      "商品の状態、傷や不具合の有無などを書いてください...",
    "give.photoLabel": "写真をアップロード（3〜5枚）*",
    "give.uploadText": "クリックして写真を選択",
    "give.submitBtn": "出品する",
    "receive.pageTitle": "必要なものをリクエスト - Mottainai Connect",
    "receive.backHome": "ホームに戻る",
    "receive.eyebrow": "もらう／買う",
    "receive.formTitle": "必要なものをリクエスト",
    "receive.formIntro":
      "探しているものと予算を入力すると、近くの人からの譲渡・販売につながりやすくなります。",
    "receive.itemLabel": "どんなものを探していますか？ *",
    "receive.itemPlaceholder": "例：炊飯器、自転車",
    "receive.locationLabel": "場所または郵便番号 *",
    "receive.locationPlaceholder": "例：Shibuya, 150-0002",
    "receive.conditionLabel": "希望する状態 *",
    "receive.conditionFree": "無料",
    "receive.conditionUsed": "中古・使用済み",
    "receive.conditionNew": "新品・新しいもの",
    "receive.selectDefault": "選択してください",
    "receive.budgetLabel": "予算・価格の範囲 *",
    "receive.noteLabel": "メモ（任意）",
    "receive.notePlaceholder": "サイズ、希望日などがあれば書いてください",
    "receive.submitBtn": "リクエストを投稿",
    "dropdown.pageTitle": "アイテムを絞り込む - Mottainai Connect",
    "dropdown.eyebrow": "検索・フィルター",
    "dropdown.title": "アイテムを絞り込む",
    "dropdown.hint": "状態を選んで、見たいアイテムだけを表示できます。",
    "dropdown.select": "選択してください",
    "dropdown.free": "無料",
    "dropdown.old": "中古",
    "dropdown.new": "新しい",
    "dropdown.result": "選択中：",
    "login.pageTitle": "ログイン - Mottainai Connect",
    "login.title": "ログイン",
    "login.description": "Mottainai Connectへようこそ",
    "login.accountLabel": "メールアドレス / 電話番号",
    "login.accountPlaceholder": "Email または電話番号",
    "login.passwordLabel": "パスワード",
    "login.passwordPlaceholder": "パスワード",
    "login.forgot": "パスワードを忘れた場合",
    "login.submit": "ログイン",
    "login.or": "または",
    "login.noAccount": "アカウントをお持ちでない方",
    "login.signup": "新規登録",
    "login.home": "ホームに戻る",
    "signup.pageTitle": "新規登録 - Mottainai Connect",
    "signup.title": "アカウントを作成",
    "signup.description": "無料でかんたんに始められます",
    "signup.nameLabel": "名前 *",
    "signup.namePlaceholder": "例：Noman",
    "signup.accountLabel": "メールアドレスまたは電話番号 *",
    "signup.accountPlaceholder": "Email または電話番号",
    "signup.passwordLabel": "パスワード *",
    "signup.passwordPlaceholder": "8文字以上がおすすめ",
    "signup.confirmLabel": "パスワード（確認） *",
    "signup.confirmPlaceholder": "もう一度入力してください",
    "signup.submit": "アカウントを作成",
    "signup.haveAccount": "すでにアカウントがありますか？",
    "signup.login": "ログイン",
    "signup.home": "ホームに戻る",
  },
};

// Base translations: English first, then compact translations for the key UI.
translations.en = {
  "nav.about": "About",
  "nav.how": "How it works",
  "nav.faq": "FAQ",
  "nav.give": "Give / Sell",
  "nav.receive": "Receive / Buy",
  "nav.login": "Login",
  "nav.logout": "Logout",
  "hero.title": "Find useful items near you",
  "hero.subtitle":
    "Make it easier to give away, reuse, and receive furniture in Japan.",
  "hero.searchPlaceholder": "Enter a postal code (e.g. 160-0022)",
  "hero.searchBtn": "Search",
  "hero.stat1": "Items exchanged",
  "hero.stat2": "Languages",
  "hero.stat3": "Volunteer reward",
  "actions.giveTitle": "Give / Sell an item",
  "actions.giveDesc": "List unused items easily with photos",
  "actions.receiveTitle": "Receive / Buy an item",
  "actions.receiveDesc": "Tell us what you need and your budget",
  "how.title": "It is simple to use",
  "how.step1Title": "Find",
  "how.step1Desc": "Search for nearby items by postal code or area.",
  "how.step2Title": "Contact",
  "how.step2Desc": "Message the person who listed or requested an item.",
  "how.step3Title": "Receive",
  "how.step3Desc": "Pick it up yourself or ask a volunteer.",
  "products.heading": "Items within 5 km",
  "common.volunteerOk": "Volunteer available",
  "p1.badge": "Free",
  "p1.title": "Wooden relaxing sofa",
  "p1.location": "Shinjuku",
  "p1.distance": "1.2 km",
  "p1.btn": "I want it",
  "p2.title": "Mini bicycle (good condition)",
  "p2.location": "Shibuya",
  "p2.distance": "3.5 km",
  "p2.btn": "Contact",
  "p3.title": "Microwave (tested)",
  "p3.location": "Koto",
  "p3.distance": "4.0 km",
  "p3.btn": "I want it",
  "volunteer.title": "Need help picking it up?",
  "volunteer.body":
    "Choose the volunteer service and a local supporter can pick up the item and deliver it to you.",
  "volunteer.bonus":
    "Rewards start from ¥300. You can also thank the supporter.",
  "volunteer.cta": "Request a volunteer",
  "about.title": "What is Mottainai Connect?",
  "about.body":
    "A community service connecting foreign residents and students in Japan so unwanted items can be reused and needed household goods can be found safely.",
  "stats.stat1": "Furniture reused",
  "stats.stat2": "Countries & regions",
  "stats.stat3": "Bulky waste reduction",
  "safety.title": "Safety guidelines",
  "safety.item1":
    "For first-time exchanges, choose a busy public place whenever possible.",
  "safety.item2": "Keep conversations in the app so there is a record.",
  "safety.item3": "Report suspicious users or inappropriate posts.",
  "safety.item4": "Only verified volunteers can handle volunteer requests.",
  "faq.title": "Frequently asked questions",
  "faq.q1": "Does it cost money?",
  "faq.a1":
    "Browsing, searching and messaging are free. A small reward from ¥300 applies only when you request a volunteer.",
  "faq.q2": "Can I use it without speaking Japanese?",
  "faq.a2":
    "Yes. You can switch languages using the language button at the top right.",
  "faq.q3": "How do we decide the pickup time?",
  "faq.a3":
    "The giver and receiver discuss a convenient time and place by message.",
  "faq.q4": "Can broken items be listed?",
  "faq.a4": "Yes, but describe the condition honestly and clearly.",
  "finalcta.title": "Turn “mottainai” into connection.",
  "finalcta.body":
    "Your unused item can become someone else’s “thank you.” Start by finding something nearby.",
  "finalcta.giveBtn": "Give an item",
  "finalcta.receiveBtn": "Request an item",
  "footer.tagline":
    "A give-and-receive support service for foreign residents and students in Japan.",
  "footer.linksTitle": "Links",
  "footer.contact": "Contact",
  "footer.rights": "© 2026 Mottainai Connect - Graduation Project",
  "give.pageTitle": "List an item - Mottainai Connect",
  "give.backHome": "Back to Home",
  "give.formTitle": "List an item (Give / Sell)",
  "give.nameLabel": "Item name *",
  "give.namePlaceholder": "e.g. Wooden table, mini fridge",
  "give.conditionLabel": "Condition *",
  "give.selectDefault": "Please select",
  "give.conditionNew": "Like new",
  "give.conditionGood": "Good condition",
  "give.conditionUsed": "Used",
  "give.priceLabel": "Price (enter 0 for free) *",
  "give.pricePlaceholder": "e.g. 1500 or 0",
  "give.locationLabel": "Location or postal code *",
  "give.locationPlaceholder": "e.g. Shinjuku, 160-0022",
  "give.descLabel": "Description *",
  "give.descPlaceholder": "Describe the condition, scratches, defects, etc.",
  "give.photoLabel": "Upload photos (3–5) *",
  "give.uploadText": "Click to choose photos",
  "give.submitBtn": "List item",
  "receive.pageTitle": "Request an item - Mottainai Connect",
  "receive.backHome": "Back to Home",
  "receive.eyebrow": "Receive / Buy",
  "receive.formTitle": "Request something you need",
  "receive.formIntro":
    "Tell the community what you need and your budget to find nearby offers.",
  "receive.itemLabel": "What are you looking for? *",
  "receive.itemPlaceholder": "e.g. Rice cooker, bicycle",
  "receive.locationLabel": "Location or postal code *",
  "receive.locationPlaceholder": "e.g. Shibuya, 150-0002",
  "receive.conditionLabel": "Preferred condition *",
  "receive.conditionFree": "Free",
  "receive.conditionUsed": "Used",
  "receive.conditionNew": "New",
  "receive.selectDefault": "Please select",
  "receive.budgetLabel": "Budget / price range *",
  "receive.noteLabel": "Note (optional)",
  "receive.notePlaceholder": "Add size, preferred date, or other details",
  "receive.submitBtn": "Post request",
  "dropdown.pageTitle": "Filter items - Mottainai Connect",
  "dropdown.eyebrow": "Search & Filter",
  "dropdown.title": "Filter items",
  "dropdown.hint": "Choose a condition to show only the items you want.",
  "dropdown.select": "Please select",
  "dropdown.free": "Free",
  "dropdown.old": "Used",
  "dropdown.new": "New",
  "dropdown.result": "Selected:",
  "login.pageTitle": "Login - Mottainai Connect",
  "login.title": "Login",
  "login.description": "Welcome to Mottainai Connect",
  "login.accountLabel": "Email / phone number",
  "login.accountPlaceholder": "Email or phone number",
  "login.passwordLabel": "Password",
  "login.passwordPlaceholder": "Password",
  "login.forgot": "Forgot password?",
  "login.submit": "Login",
  "login.or": "or",
  "login.noAccount": "Don't have an account?",
  "login.signup": "Sign up",
  "login.home": "Back to Home",
  "signup.pageTitle": "Sign up - Mottainai Connect",
  "signup.title": "Create your account",
  "signup.description": "Start for free in a few simple steps",
  "signup.nameLabel": "Name *",
  "signup.namePlaceholder": "e.g. Noman",
  "signup.accountLabel": "Email or phone number *",
  "signup.accountPlaceholder": "Email or phone number",
  "signup.passwordLabel": "Password *",
  "signup.passwordPlaceholder": "8 characters or more is recommended",
  "signup.confirmLabel": "Confirm password *",
  "signup.confirmPlaceholder": "Enter it again",
  "signup.submit": "Create account",
  "signup.haveAccount": "Already have an account?",
  "signup.login": "Login",
  "signup.home": "Back to Home",
};

// Reuse English as a safe fallback for languages not fully translated below.
for (const code of LANGUAGES)
  if (!translations[code]) translations[code] = { ...translations.en };

// Common UI translations for the 10 additional languages. Missing page-specific keys fall back to English.
Object.assign(translations.zh, {
  "nav.logout": "退出登录",
  "nav.about": "关于 Mottainai Connect",
  "nav.how": "使用方法",
  "nav.faq": "常见问题",
  "nav.give": "赠送 / 出售",
  "nav.receive": "领取 / 购买",
  "nav.login": "登录",
  "hero.title": "寻找附近需要再利用的物品",
  "hero.searchBtn": "搜索",
  "actions.giveTitle": "赠送 / 出售物品",
  "actions.receiveTitle": "领取 / 购买物品",
  "how.title": "使用方法很简单",
  "products.heading": "距离当前位置 5 公里的物品",
  "give.formTitle": "发布物品（赠送 / 出售）",
  "give.submitBtn": "发布",
  "receive.formTitle": "发布求物请求",
  "receive.submitBtn": "发布请求",
  "login.title": "登录",
  "login.submit": "登录",
  "login.signup": "注册",
  "signup.title": "创建账户",
  "signup.submit": "创建账户",
});
Object.assign(translations.bn, {
  "nav.logout": "লগআউট",
  "nav.about": "Mottainai Connect কী?",
  "nav.how": "কীভাবে ব্যবহার করবেন",
  "nav.faq": "সাধারণ প্রশ্ন",
  "nav.give": "দেওয়া / বিক্রি",
  "nav.receive": "নেওয়া / কেনা",
  "nav.login": "লগইন",
  "hero.title": "আপনার কাছাকাছি প্রয়োজনীয় জিনিস খুঁজুন",
  "hero.subtitle": "জাপানে আসবাবপত্র দেওয়া, পুনঃব্যবহার ও নেওয়া সহজ করুন।",
  "hero.searchBtn": "খুঁজুন",
  "actions.giveTitle": "জিনিস দেওয়া / বিক্রি",
  "actions.receiveTitle": "জিনিস নেওয়া / কেনা",
  "how.title": "ব্যবহার করা খুব সহজ",
  "products.heading": "আপনার জায়গা থেকে ৫ কিমির মধ্যে",
  "give.formTitle": "জিনিস পোস্ট করুন (দেওয়া / বিক্রি)",
  "give.submitBtn": "পোস্ট করুন",
  "receive.formTitle": "প্রয়োজনীয় জিনিসের অনুরোধ",
  "receive.submitBtn": "রিকোয়েস্ট পোস্ট করুন",
  "login.title": "লগইন",
  "login.submit": "লগইন",
  "login.signup": "সাইন আপ",
  "signup.title": "অ্যাকাউন্ট তৈরি করুন",
  "signup.submit": "অ্যাকাউন্ট তৈরি করুন",
});
Object.assign(translations.ne, {
  "nav.logout": "लगआउट",
  "nav.about": "Mottainai Connect बारे",
  "nav.how": "कसरी प्रयोग गर्ने",
  "nav.faq": "सामान्य प्रश्न",
  "nav.give": "दिने / बेच्ने",
  "nav.receive": "लिने / किन्ने",
  "nav.login": "लगइन",
  "hero.title": "तपाईं नजिकका उपयोगी सामान खोज्नुहोस्",
  "hero.searchBtn": "खोज्नुहोस्",
  "actions.giveTitle": "सामान दिने / बेच्ने",
  "actions.receiveTitle": "सामान लिने / किन्ने",
  "how.title": "प्रयोग गर्न धेरै सजिलो छ",
  "give.formTitle": "सामान पोस्ट गर्नुहोस्",
  "give.submitBtn": "पोस्ट गर्नुहोस्",
  "receive.formTitle": "चाहिएको सामान अनुरोध गर्नुहोस्",
  "receive.submitBtn": "अनुरोध पोस्ट गर्नुहोस्",
  "login.title": "लगइन",
  "login.submit": "लगइन",
  "login.signup": "साइन अप",
  "signup.title": "खाता बनाउनुहोस्",
  "signup.submit": "खाता बनाउनुहोस्",
});
Object.assign(translations.vi, {
  "nav.logout": "Đăng xuất",
  "nav.about": "Về Mottainai Connect",
  "nav.how": "Cách sử dụng",
  "nav.faq": "Câu hỏi thường gặp",
  "nav.give": "Cho / Bán",
  "nav.receive": "Nhận / Mua",
  "nav.login": "Đăng nhập",
  "hero.title": "Tìm đồ hữu ích gần bạn",
  "hero.searchBtn": "Tìm kiếm",
  "actions.giveTitle": "Cho / Bán đồ",
  "actions.receiveTitle": "Nhận / Mua đồ",
  "how.title": "Cách sử dụng rất đơn giản",
  "give.formTitle": "Đăng đồ (Cho / Bán)",
  "give.submitBtn": "Đăng đồ",
  "receive.formTitle": "Yêu cầu món đồ cần thiết",
  "receive.submitBtn": "Đăng yêu cầu",
  "login.title": "Đăng nhập",
  "login.submit": "Đăng nhập",
  "login.signup": "Đăng ký",
  "signup.title": "Tạo tài khoản",
  "signup.submit": "Tạo tài khoản",
});
Object.assign(translations.ta, {
  "nav.logout": "வெளியேறு",
  "nav.about": "Mottainai Connect பற்றி",
  "nav.how": "எப்படி பயன்படுத்துவது",
  "nav.faq": "அடிக்கடி கேட்கப்படும் கேள்விகள்",
  "nav.give": "கொடுக்க / விற்க",
  "nav.receive": "பெற / வாங்க",
  "nav.login": "உள்நுழைவு",
  "hero.title": "உங்களுக்கு அருகிலுள்ள பொருட்களை கண்டுபிடிக்கவும்",
  "hero.searchBtn": "தேடு",
  "actions.giveTitle": "பொருளை கொடுக்க / விற்க",
  "actions.receiveTitle": "பொருளை பெற / வாங்க",
  "how.title": "பயன்படுத்துவது மிகவும் எளிது",
  "give.formTitle": "பொருளை பதிவு செய்யவும்",
  "give.submitBtn": "பதிவு செய்",
  "receive.formTitle": "தேவையான பொருளை கோருங்கள்",
  "receive.submitBtn": "கோரிக்கையை பதிவு செய்",
  "login.title": "உள்நுழைவு",
  "login.submit": "உள்நுழைவு",
  "login.signup": "பதிவு செய்",
  "signup.title": "கணக்கை உருவாக்கவும்",
  "signup.submit": "கணக்கை உருவாக்கவும்",
});
Object.assign(translations.my, {
  "nav.logout": "ထွက်ရန်",
  "nav.about": "Mottainai Connect အကြောင်း",
  "nav.how": "အသုံးပြုနည်း",
  "nav.faq": "မေးလေ့ရှိသောမေးခွန်းများ",
  "nav.give": "ပေး / ရောင်း",
  "nav.receive": "ယူ / ဝယ်",
  "nav.login": "ဝင်ရောက်ရန်",
  "hero.title": "သင့်အနီးရှိ အသုံးဝင်သောပစ္စည်းများကို ရှာပါ",
  "hero.searchBtn": "ရှာရန်",
  "actions.giveTitle": "ပစ္စည်းပေး / ရောင်း",
  "actions.receiveTitle": "ပစ္စည်းယူ / ဝယ်",
  "how.title": "အသုံးပြုရန် လွယ်ကူပါသည်",
  "give.formTitle": "ပစ္စည်းတင်ရန်",
  "give.submitBtn": "တင်ရန်",
  "receive.formTitle": "လိုအပ်သောပစ္စည်း တောင်းရန်",
  "receive.submitBtn": "တောင်းဆိုချက်တင်ရန်",
  "login.title": "ဝင်ရောက်ရန်",
  "login.submit": "ဝင်ရောက်ရန်",
  "login.signup": "စာရင်းသွင်းရန်",
  "signup.title": "အကောင့်ဖန်တီးရန်",
  "signup.submit": "အကောင့်ဖန်တီးရန်",
});
Object.assign(translations.id, {
  "nav.logout": "Keluar",
  "nav.about": "Tentang Mottainai Connect",
  "nav.how": "Cara menggunakan",
  "nav.faq": "FAQ",
  "nav.give": "Berikan / Jual",
  "nav.receive": "Terima / Beli",
  "nav.login": "Masuk",
  "hero.title": "Temukan barang berguna di dekat Anda",
  "hero.searchBtn": "Cari",
  "actions.giveTitle": "Berikan / Jual barang",
  "actions.receiveTitle": "Terima / Beli barang",
  "how.title": "Cara menggunakannya sangat mudah",
  "give.formTitle": "Pasang barang (Berikan / Jual)",
  "give.submitBtn": "Pasang",
  "receive.formTitle": "Minta barang yang dibutuhkan",
  "receive.submitBtn": "Kirim permintaan",
  "login.title": "Masuk",
  "login.submit": "Masuk",
  "login.signup": "Daftar",
  "signup.title": "Buat akun",
  "signup.submit": "Buat akun",
});
Object.assign(translations.fil, {
  "nav.logout": "Mag-logout",
  "nav.about": "Tungkol sa Mottainai Connect",
  "nav.how": "Paano gamitin",
  "nav.faq": "Mga FAQ",
  "nav.give": "Magbigay / Magbenta",
  "nav.receive": "Tumanggap / Bumili",
  "nav.login": "Mag-login",
  "hero.title": "Maghanap ng kapaki-pakinabang na bagay malapit sa iyo",
  "hero.searchBtn": "Maghanap",
  "actions.giveTitle": "Magbigay / Magbenta ng gamit",
  "actions.receiveTitle": "Tumanggap / Bumili ng gamit",
  "how.title": "Madali lang gamitin",
  "give.formTitle": "I-post ang gamit",
  "give.submitBtn": "I-post",
  "receive.formTitle": "Humiling ng kailangan mong gamit",
  "receive.submitBtn": "I-post ang request",
  "login.title": "Mag-login",
  "login.submit": "Mag-login",
  "login.signup": "Mag-sign up",
  "signup.title": "Gumawa ng account",
  "signup.submit": "Gumawa ng account",
});
Object.assign(translations.pt, {
  "nav.logout": "Sair",
  "nav.about": "Sobre o Mottainai Connect",
  "nav.how": "Como usar",
  "nav.faq": "Perguntas frequentes",
  "nav.give": "Doar / Vender",
  "nav.receive": "Receber / Comprar",
  "nav.login": "Entrar",
  "hero.title": "Encontre itens úteis perto de você",
  "hero.searchBtn": "Pesquisar",
  "actions.giveTitle": "Doar / Vender item",
  "actions.receiveTitle": "Receber / Comprar item",
  "how.title": "É muito simples de usar",
  "give.formTitle": "Anunciar item",
  "give.submitBtn": "Anunciar",
  "receive.formTitle": "Solicitar um item necessário",
  "receive.submitBtn": "Publicar pedido",
  "login.title": "Entrar",
  "login.submit": "Entrar",
  "login.signup": "Criar conta",
  "signup.title": "Criar sua conta",
  "signup.submit": "Criar conta",
});
Object.assign(translations.ko, {
  "nav.logout": "로그아웃",
  "nav.about": "Mottainai Connect 소개",
  "nav.how": "사용 방법",
  "nav.faq": "자주 묻는 질문",
  "nav.give": "나눔 / 판매",
  "nav.receive": "받기 / 구매",
  "nav.login": "로그인",
  "hero.title": "내 주변의 필요한 물건을 찾아보세요",
  "hero.searchBtn": "검색",
  "actions.giveTitle": "물건 나눔 / 판매",
  "actions.receiveTitle": "물건 받기 / 구매",
  "how.title": "사용 방법은 아주 간단합니다",
  "give.formTitle": "물건 등록 (나눔 / 판매)",
  "give.submitBtn": "등록하기",
  "receive.formTitle": "필요한 물건 요청하기",
  "receive.submitBtn": "요청 등록",
  "login.title": "로그인",
  "login.submit": "로그인",
  "login.signup": "회원가입",
  "signup.title": "계정 만들기",
  "signup.submit": "계정 만들기",
});

function getCurrentLanguage() {
  return localStorage.getItem("mottainai_language") || "ja";
}
function translate(key, lang = getCurrentLanguage()) {
  return (
    (translations[lang] && translations[lang][key]) ||
    translations.en[key] ||
    translations.ja[key] ||
    key
  );
}

function applyLanguage() {
  const lang = getCurrentLanguage();
  document.documentElement.lang = lang;
  document.querySelectorAll("[data-i18n]").forEach((el) => {
    const key = el.dataset.i18n;
    if (el.dataset.i18nHtml === "true") el.innerHTML = translate(key, lang);
    else el.textContent = translate(key, lang);
  });
  document.querySelectorAll("[data-i18n-placeholder]").forEach((el) => {
    el.placeholder = translate(el.dataset.i18nPlaceholder, lang);
  });
  const title = document.querySelector("title[data-i18n]");
  if (title) document.title = translate(title.dataset.i18n, lang);
  document
    .querySelectorAll(".btn-lang")
    .forEach((b) => b.classList.toggle("active", b.dataset.lang === lang));
  const en = document.getElementById("btn-en");
  if (en && lang !== "ja")
    en.firstChild.textContent = LANGUAGE_NAMES[lang] + " ";
  if (en && lang === "ja") en.firstChild.textContent = "English ";
}

function changeLanguage(lang) {
  if (!LANGUAGES.includes(lang)) lang = "ja";
  localStorage.setItem("mottainai_language", lang);
  applyLanguage();
}

window.changeLanguage = changeLanguage;
window.applyLanguage = applyLanguage;
window.translate = translate;
window.getCurrentLanguage = getCurrentLanguage;

document.addEventListener("DOMContentLoaded", applyLanguage);
